### ISSUE TITLE
希望集成openssl以及中文

### ISSUE THREAD

**Issue by fcwys** [deviousasti/openssl-wizard#3]
希望集成openssl以及中文以方便使用，此外文件路径建议添加浏览按钮以自定义路径

**Comment by deviousasti** [comment]
If you installed using chocolatey, whichever directory you open openssl-wizard in will be the directory to which it writes.
![image](https://user-images.githubusercontent.com/2375486/93625259-48b4b300-f9ff-11ea-8a00-42ee61bf7bdc.png)

But I will add an option to be able to select the output directory.
